name: Zig CI

on:
  push:
    branches: [ zig ]
  pull_request:
    branches: [ zig ]

jobs:
  build_all_platforms:
    name: Build on Ubuntu (Linux & Windows targets)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Zig (0.11.0)
      uses: mlugg/setup-zig@v1
      with:
        version: "0.11.0"

    # Build for Linux (native)
    - name: Build executable (Linux)
      run: zig build
      # Output will be in zig-out/bin/app

    - name: Upload executable (Linux)
      uses: actions/upload-artifact@v4
      with:
        name: app-linux
        path: zig-out/bin/app

    # Build for Windows (cross-compilation)
    - name: Clean previous build (for Windows target)
      run: rm -rf zig-out zig-cache

    - name: Build executable (Windows x64)
      run: zig build -Dtarget=x86_64-windows-gnu
      # Output will be in zig-out/bin/app.exe

    - name: Upload executable (Windows)
      uses: actions/upload-artifact@v4
      with:
        name: app-windows
        path: zig-out/bin/app.exe
