name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --config Release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my_project_ubuntu
        path: build/my_project

  build_windows:
    runs-on: windows-latest
    env:
      BUILD_CONFIG: Release # Define an environment variable for build configuration
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_CONFIG }}
    - name: Build
      run: cmake --build build --config ${{ env.BUILD_CONFIG }}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my_project_windows
        path: build/${{ env.BUILD_CONFIG }}/my_project.exe
