name: Zig CI

on:
  push:
    branches: [ zig ]
  pull_request:
    branches: [ zig ]

jobs:
  build_all_platforms:
    name: Build on Ubuntu (Linux & Windows targets)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mlugg/setup-zig@v2

    # Install hidapi for Linux
    - name: Install hidapi dependencies and build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev libusb-1.0-0-dev pkg-config autoconf automake libtool
    - name: Clone hidapi repository
      run: git clone https://github.com/libusb/hidapi.git hidapi_src
    - name: Build and install hidapi
      run: |
        cd hidapi_src
        ./bootstrap
        ./configure --prefix=$GITHUB_WORKSPACE/hidapi_install CFLAGS="-fPIC"
        make
        make install
        cd ..

    # Build for Linux (native)
    - name: Build executable (Linux)
      run: zig build
      # Output will be in zig-out/bin/app

    - name: Run HID device lister
      run: ./zig-out/bin/app

    - name: Upload executable (Linux)
      uses: actions/upload-artifact@v4
      with:
        name: app-linux
        path: zig-out/bin/app

    # Build for Windows (cross-compilation)
    - name: Clean previous build (for Windows target)
      run: rm -rf zig-out zig-cache

    - name: Build executable (Windows x64)
      run: zig build -Dtarget=x86_64-windows-gnu
      # Output will be in zig-out/bin/app.exe

    - name: Upload executable (Windows)
      uses: actions/upload-artifact@v4
      with:
        name: app-windows
        path: zig-out/bin/app.exe
