name: Zig CI

on:
  push:
    branches: [ zig ] # Changed from main to zig
  pull_request:
    branches: [ zig ] # Changed from main to zig

jobs:
  build_zig_executables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Zig (latest)
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: latest # Specify latest version

    - name: Build executables
      run: zig build

    - name: Upload hello executable
      uses: actions/upload-artifact@v4
      with:
        name: hello_executable_ubuntu
        path: zig-out/bin/hello

    - name: Upload hello2 executable
      uses: actions/upload-artifact@v4
      with:
        name: hello2_executable_ubuntu
        path: zig-out/bin/hello2
